//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_CompanyBank
    {
        public System.Guid BankId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string BranchAddress1 { get; set; }
        public string BranchAddress2 { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string SwiftCde { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
