//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_CompanyMast
    {
        public System.Guid CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WebStite { get; set; }
        public string Fax { get; set; }
        public string RegisterAddress1 { get; set; }
        public string RegisterAddress2 { get; set; }
        public string RegisterPincode { get; set; }
        public string FactoryAddress1 { get; set; }
        public string FactoryAddress2 { get; set; }
        public string FactoryPincode { get; set; }
        public string GSTNo { get; set; }
        public string PANNo { get; set; }
        public string CINNo { get; set; }
        public string ECCNo { get; set; }
        public string IECCode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DefaultCurrencyId { get; set; }
        public string FromEmail { get; set; }
        public string DisplayName { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public string SmtpUsername { get; set; }
        public string SmtpPassword { get; set; }
        public Nullable<int> RegiterCityId { get; set; }
        public Nullable<int> RegiterStateId { get; set; }
        public Nullable<int> RegisterCountryId { get; set; }
        public Nullable<int> FactoryCityId { get; set; }
        public Nullable<int> FactoryStateId { get; set; }
        public Nullable<int> FactoryCountryId { get; set; }
    }
}
