//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FormTab
    {
        public System.Guid FormTabId { get; set; }
        public System.Guid FormId { get; set; }
        public System.Guid FormSectionId { get; set; }
        public string TabName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string TabTitle { get; set; }
        public string TabSQLTableName { get; set; }
        public string NextTabDataScript { get; set; }
    }
}
