//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FormMast
    {
        public System.Guid FormId { get; set; }
        public string FormName { get; set; }
        public string FormTitle { get; set; }
        public string FormDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> ParentFormId { get; set; }
        public string SQLTableName { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<int> SqlTemplateId { get; set; }
        public string Alias { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
