//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FormFieldOption
    {
        public System.Guid OptionId { get; set; }
        public System.Guid FieldId { get; set; }
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
