//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FormField
    {
        public System.Guid FieldId { get; set; }
        public System.Guid FormId { get; set; }
        public Nullable<System.Guid> FormTabId { get; set; }
        public System.Guid FieldTypeId { get; set; }
        public bool IsActive { get; set; }
        public string FieldName { get; set; }
        public string FieldCaption { get; set; }
        public int FieldLength { get; set; }
        public Nullable<System.Guid> FormSectionId { get; set; }
        public bool IsRequired { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> ParameterId { get; set; }
        public string DDLSourceType { get; set; }
        public string DDLSourceName { get; set; }
        public string DDLTextField { get; set; }
        public string DDLValueField { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsVisibleInList { get; set; }
        public string FieldSize { get; set; }
        public string FieldPlaceHolder { get; set; }
        public string FieldHelpText { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string FieldFormula { get; set; }
        public Nullable<bool> IsDependencyField { get; set; }
        public Nullable<bool> IsMultiSelection { get; set; }
        public Nullable<bool> IsUnique { get; set; }
        public Nullable<int> FieldDecimal { get; set; }
        public Nullable<bool> AllowMultiDocument { get; set; }
        public Nullable<bool> IsSummary { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<bool> IsTimeField { get; set; }
        public string FieldFormat { get; set; }
    }
}
