//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_UserMast
    {
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> PasswordExpiredOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> DefaultDashboardId { get; set; }
    }
}
