//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_UserSettings
    {
        public int UserSettingId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid CompanyId { get; set; }
        public int DefaultFiancialYearId { get; set; }
    }
}
