//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDSolution.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TFDSolutionEntities : DbContext
    {
        public TFDSolutionEntities()
            : base("name=TFDSolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_FormFieldOption> m_FormFieldOption { get; set; }
        public virtual DbSet<m_FormSection> m_FormSection { get; set; }
        public virtual DbSet<m_FormTab> m_FormTab { get; set; }
        public virtual DbSet<m_UserMast> m_UserMast { get; set; }
        public virtual DbSet<m_CompanyBank> m_CompanyBank { get; set; }
        public virtual DbSet<m_CompanyFinancials> m_CompanyFinancials { get; set; }
        public virtual DbSet<m_UserSettings> m_UserSettings { get; set; }
        public virtual DbSet<m_FormFieldTypes> m_FormFieldTypes { get; set; }
        public virtual DbSet<m_FormMast> m_FormMast { get; set; }
        public virtual DbSet<m_CompanyUnit> m_CompanyUnit { get; set; }
        public virtual DbSet<m_FormField> m_FormField { get; set; }
        public virtual DbSet<m_CompanyMast> m_CompanyMast { get; set; }
    
        public virtual ObjectResult<m_setUser_Result> m_setUser(string p_action, Nullable<System.Guid> userId, string firstName, string lastName, string emailId, string userName, string password, Nullable<bool> isActive)
        {
            var p_actionParameter = p_action != null ?
                new ObjectParameter("p_action", p_action) :
                new ObjectParameter("p_action", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<m_setUser_Result>("m_setUser", p_actionParameter, userIdParameter, firstNameParameter, lastNameParameter, emailIdParameter, userNameParameter, passwordParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<auth_getLogin_Result> auth_getLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<auth_getLogin_Result>("auth_getLogin", userNameParameter, passwordParameter);
        }
    
        public virtual int m_getNextCode(string p_tableName)
        {
            var p_tableNameParameter = p_tableName != null ?
                new ObjectParameter("p_tableName", p_tableName) :
                new ObjectParameter("p_tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("m_getNextCode", p_tableNameParameter);
        }
    
        public virtual ObjectResult<proc_AddCompany_Result> proc_AddCompany(string companyCode, string companyName, string createdBy, string email, string phone, string mobile)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AddCompany_Result>("proc_AddCompany", companyCodeParameter, companyNameParameter, createdByParameter, emailParameter, phoneParameter, mobileParameter);
        }
    
        public virtual ObjectResult<proc_getCompanyList_Result> proc_getCompanyList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getCompanyList_Result>("proc_getCompanyList");
        }
    
        public virtual ObjectResult<proc_getItem_Result> proc_getItem(string uId)
        {
            var uIdParameter = uId != null ?
                new ObjectParameter("UId", uId) :
                new ObjectParameter("UId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getItem_Result>("proc_getItem", uIdParameter);
        }
    
        public virtual ObjectResult<m_getSelection_Result> m_getSelection(string selectionType, string whereClause, string orderBy, string entryType)
        {
            var selectionTypeParameter = selectionType != null ?
                new ObjectParameter("SelectionType", selectionType) :
                new ObjectParameter("SelectionType", typeof(string));
    
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var entryTypeParameter = entryType != null ?
                new ObjectParameter("EntryType", entryType) :
                new ObjectParameter("EntryType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<m_getSelection_Result>("m_getSelection", selectionTypeParameter, whereClauseParameter, orderByParameter, entryTypeParameter);
        }
    
        public virtual ObjectResult<proc_AddItem_Result> proc_AddItem(string itemCode, string itemDescription, string alternateDescription, Nullable<int> itemGroup, Nullable<int> itemUOM, Nullable<int> itemCategory, Nullable<int> itemType, Nullable<int> packingType, Nullable<bool> itemStatus, Nullable<System.Guid> userId)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var itemDescriptionParameter = itemDescription != null ?
                new ObjectParameter("ItemDescription", itemDescription) :
                new ObjectParameter("ItemDescription", typeof(string));
    
            var alternateDescriptionParameter = alternateDescription != null ?
                new ObjectParameter("AlternateDescription", alternateDescription) :
                new ObjectParameter("AlternateDescription", typeof(string));
    
            var itemGroupParameter = itemGroup.HasValue ?
                new ObjectParameter("ItemGroup", itemGroup) :
                new ObjectParameter("ItemGroup", typeof(int));
    
            var itemUOMParameter = itemUOM.HasValue ?
                new ObjectParameter("ItemUOM", itemUOM) :
                new ObjectParameter("ItemUOM", typeof(int));
    
            var itemCategoryParameter = itemCategory.HasValue ?
                new ObjectParameter("ItemCategory", itemCategory) :
                new ObjectParameter("ItemCategory", typeof(int));
    
            var itemTypeParameter = itemType.HasValue ?
                new ObjectParameter("ItemType", itemType) :
                new ObjectParameter("ItemType", typeof(int));
    
            var packingTypeParameter = packingType.HasValue ?
                new ObjectParameter("PackingType", packingType) :
                new ObjectParameter("PackingType", typeof(int));
    
            var itemStatusParameter = itemStatus.HasValue ?
                new ObjectParameter("ItemStatus", itemStatus) :
                new ObjectParameter("ItemStatus", typeof(bool));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AddItem_Result>("proc_AddItem", itemCodeParameter, itemDescriptionParameter, alternateDescriptionParameter, itemGroupParameter, itemUOMParameter, itemCategoryParameter, itemTypeParameter, packingTypeParameter, itemStatusParameter, userIdParameter);
        }
    
        public virtual ObjectResult<proc_getItemList_Result> proc_getItemList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getItemList_Result>("proc_getItemList");
        }
    
        public virtual ObjectResult<proc_getParty_Result> proc_getParty(string uId)
        {
            var uIdParameter = uId != null ?
                new ObjectParameter("UId", uId) :
                new ObjectParameter("UId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getParty_Result>("proc_getParty", uIdParameter);
        }
    
        public virtual ObjectResult<proc_getPartyList_Result> proc_getPartyList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getPartyList_Result>("proc_getPartyList");
        }
    
        public virtual ObjectResult<m_getFormData_Result> m_getFormData(string formId)
        {
            var formIdParameter = formId != null ?
                new ObjectParameter("FormId", formId) :
                new ObjectParameter("FormId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<m_getFormData_Result>("m_getFormData", formIdParameter);
        }
    
        public virtual ObjectResult<m_getFormFields_Result> m_getFormFields(string formId, string sectionId, string tabId)
        {
            var formIdParameter = formId != null ?
                new ObjectParameter("FormId", formId) :
                new ObjectParameter("FormId", typeof(string));
    
            var sectionIdParameter = sectionId != null ?
                new ObjectParameter("SectionId", sectionId) :
                new ObjectParameter("SectionId", typeof(string));
    
            var tabIdParameter = tabId != null ?
                new ObjectParameter("TabId", tabId) :
                new ObjectParameter("TabId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<m_getFormFields_Result>("m_getFormFields", formIdParameter, sectionIdParameter, tabIdParameter);
        }
    
        public virtual ObjectResult<m_getForms_Result> m_getForms(string formId)
        {
            var formIdParameter = formId != null ?
                new ObjectParameter("FormId", formId) :
                new ObjectParameter("FormId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<m_getForms_Result>("m_getForms", formIdParameter);
        }
    }
}
