
CREATE TABLE AuditLogs
(
    AuditLogId INT IDENTITY(1,1) PRIMARY KEY,
    LogDateTime DATETIME NOT NULL DEFAULT GETDATE(),
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    FinancialYearId INT NULL,
    PageName NVARCHAR(200) NOT  NULL,
    Action NVARCHAR(100) NOT NULL,
    RecordId NVARCHAR(100)  NULL,
    FieldName NVARCHAR(100) NULL,
    FieldOldValue NVARCHAR(MAX) NULL,
    FieldNewValue NVARCHAR(MAX) NULL,
	IPAddress NVARCHAR(45) NULL,
    Remark NVARCHAR(500) NULL
);