DROP TABLE IF EXISTS m_RoleMast
GO

CREATE TABLE m_RoleMast (
    RoleId INT IDENTITY(1,1) PRIMARY KEY,
    RoleName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255) NULL,
    CreatedOn DATETIME NOT NULL DEFAULT GETDATE(),
    Status BIT DEFAULT(1)NOT NULL
);

